import { ISize, ISizePayload } from "../types/product-size.types";

const API_BASE_URL = "http://localhost:5000/api";

export async function fetchSizes(): Promise<ISize[]> {
    try {
        const response = await fetch(`${API_BASE_URL}/sizes`);

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.message);
        }

        return await response.json();
    } catch (error: any) {
        throw new Error(error?.message || "Помилка з'єднання із сервером");
    }
}

export async function createSize(data: ISizePayload): Promise<ISize> {
    try {
        const response = await fetch(`${API_BASE_URL}/sizes`, {
            method: "POST",
            credentials: "include",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.message);
        }

        return await response.json();
    } catch (error: any) {
        throw new Error(error?.message || "Помилка з'єднання із сервером");
    }
}

export async function editSize(sizeId: ISize["id"], data: Partial<ISize>): Promise<ISize> {
    try {
        const response = await fetch(`${API_BASE_URL}/sizes/${sizeId}`, {
            method: "PATCH",
            credentials: "include",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.message);
        }

        return await response.json();
    } catch (error: any) {
        throw new Error(error?.message || "Помилка з'єднання із сервером");
    }
}

export async function deleteSize(sizeId: ISize["id"]): Promise<void> {
    try {
        const response = await fetch(`${API_BASE_URL}/sizes/${sizeId}`, {
            method: "DELETE",
            credentials: "include",
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.message);
        }

        return await response.json();
    } catch (error: any) {
        throw new Error(error?.message || "Помилка з'єднання із сервером");
    }
}
